# Travis-CI file for pyDatView
language: python

python:
  - "3.6"
  - "3.7"
os: 
 - linux
sudo: true

install:
  - sudo apt-get install nsis
  - pip install -r ressources/travis_requirements.txt

script: 
  - make tests
  - if [[ "$TRAVIS_TAG" == "" ]]; then export TRAVIS_TAG="vdev" ; fi

before_deploy:
  - git fetch --unshallow
  - export VERSION_NAME=`git describe | sed 's/\(.*\)-.*/\1/'`
  - export FULL_VERSION_NAME="version $VERSION_NAME"
  - if [[ "$TRAVIS_TAG" == "vdev" ]]; then export VERSION_NAME=$VERSION_NAME"-dev" ; fi
  - if [[ "$TRAVIS_TAG" == "vdev" ]]; then export FULL_VERSION_NAME="latest dev. version $VERSION_NAME" ; fi
  - echo $VERSION_NAME
  - pip install pynsist
  - pip install distlib
  - git clone https://github.com/takluyver/pynsist
  - mv pynsist/nsist nsist 
  - make installer
  - mv build/nsis/viz3danim.exe "viz3danim_"$VERSION_NAME"_setup.exe"
  - mv build/nsis build/viz3danim_$VERSION_NAME
  - cd build && zip -r "../viz3danim_"$VERSION_NAME"_portable.zip" pyDatView_$VERSION_NAME
  - cd ..
  - ls

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  overwrite:  true
  skip_cleanup: true
  file:
      - viz3danim*.exe
      - viz3danim*.zip
  name: $FULL_VERSION_NAME
  target_commitish: $TRAVIS_COMMIT 
  tag_name: $TRAVIS_TAG 
  on:
     tags: true
     branch: master
     condition: $TRAVIS_PYTHON_VERSION = 3.6
